Добавлен запрос из бэкенда к сервису классификации
Flexberry/Flexberry.TextClassifierAI.Sample pull request #10
Opened 2023-09-14 07:17 UTC by BannikovRuslan

feat: добавлен запрос из бэкенда к сервису классификации

2023-09-14 08:21 UTC, AntonIV8 requested changes

2023-09-14 08:21 UTC, AntonIV8 commented on src/ReportsTextClassifierAi/ODataBackend/Classification/ClassificatorTools.cs
> +    public static class ClassificatorTools
Лучше ClassificatorService или еще Понятнее ClassificatorHttpService. Ну и в комментарии к классу. Этот класс у тебя ведь только по сети предполагает взаимодействие ?

Ну и еще момент, что у нас где-то Classifier пишется, а где-то Classificator, переводится одинаково, но надо бы что-то одно выбрать

2023-09-14 08:21 UTC, AntonIV8 commented on src/ReportsTextClassifierAi/ODataBackend/Classification/ClassificatorTools.cs
> +        public static string GetTextCategoryRequest(string classificatorUrl, string fileName, string text)
Тоже не понятно по названию метода что он делает. Он же отправляет запрос классификатору, чтобы тот вынес вердикт. А по названию метод "Возвращает запрос категории текста"

2023-09-14 08:21 UTC, AntonIV8 commented on src/ReportsTextClassifierAi/ODataBackend/Classification/ClassificatorTools.cs
> +            string requestUrl = "classify";
Это должно быть в параметрах метода

2023-09-14 08:21 UTC, AntonIV8 commented on src/ReportsTextClassifierAi/ODataBackend/appsettings.json
> +  "ClassifiercUrl": "http://localhost:8000"
Опечатка видимо. 
и добавить эту настройку в docker-compose, т.к там не localhost будет

2023-09-14 11:26 UTC, BannikovRuslan commented on src/ReportsTextClassifierAi/ODataBackend/Classification/ClassificatorTools.cs
> +            string requestUrl = "classify";
Предполагается, что этот метод будет только выполнять запрос на получение категории, т.е. всегда  к узлу classify.

2023-09-14 12:37 UTC, AntonIV8 approved these changes

2023-09-14 17:58 UTC, TeterinaSvetlana commented on src/ReportsTextClassifierAi/ODataBackend/Classification/ReportFileClassifier.cs
> +                throw new HttpRequestException("Text category getting error!\n" + ex.Message);
мне кажется лучше "Error getting text category"

2023-09-14 17:58 UTC, TeterinaSvetlana approved these changes

2023-09-15 03:45 UTC, VChurekov approved these changes

2023-09-15 03:45 UTC, VChurekov commented on src/ReportsTextClassifierAi/ODataBackend/Classification/ClassifierHttpService.cs
> +                    throw new HttpRequestException("Post request sended error!\n" + ex.Message);
Тут тоже в тексте ошибки лучше слово Error в начале.

2023-09-15 04:48 UTC, merged