Обученная модель классификатора.
Flexberry/Flexberry.TextClassifierAI.Sample pull request #16
Opened 2023-09-15 11:35 UTC by BannikovRuslan

2023-09-15 12:08 UTC, AntonIV8 requested changes

2023-09-15 12:08 UTC, AntonIV8 commented on src/Docker/Dockerfile.ScikitLearnClassifier
> +RUN pip install python-multipart
А это зачем ?

2023-09-15 12:14 UTC, BannikovRuslan commented on src/Docker/Dockerfile.ScikitLearnClassifier
> +RUN pip install python-multipart
Для отправки данных через формы. А так ошибка вылетала при запуске и просил установить этот модуль.

2023-09-18 03:58 UTC, AntonIV8 commented on src/Docker/Dockerfile.ScikitLearnClassifier
> +RUN pip install python-multipart
Что за формы ? И что именно просит этот пакет ?

2023-09-18 09:45 UTC, AntonIV8 approved these changes

2023-09-18 09:45 UTC, merged