Тестирование нейронной сети PyTorch с загрузкой изображений из CSV файла.
Flexberry/Flexberry.TextClassifierAI.Sample pull request #22
Opened 2023-09-26 09:29 UTC by VChurekov

2023-09-26 13:07 UTC, BannikovRuslan commented on src/PyTorchClassifierCSVDataset/main.py
> +!pip install torchtext spacy
Зачем первая строчка?

2023-09-26 13:14 UTC, BannikovRuslan commented on src/PyTorchClassifierCSVDataset/main.py
> +class CustomCSVDataset(Dataset):
Объявление класса посреди исполняемой основной части. Тоже касается и дальше отдельных функций, объявляются внутри исполняемого кода.
Лучше бы, конечно:
1. Вынести все классы в отдельные файлы.
2. Основной исполняемый код занести под `if __name__ == "__main__":` - определяет точку входа в приложение.

2023-09-26 18:24 UTC, AntonIV8 requested changes

2023-09-26 18:24 UTC, AntonIV8 commented on src/PyTorchClassifierCSVDataset/Readme.md
> +Отличительной особенностью является метод **CustomCSVDataset** для получение набора данных из CSV файла.
Все-таки еще бы инфы добавить немного. Например, что скрипт предназначен для colab, пока не очень понятно, и замечание Руслана про pip install в коде справедливо.
Также поясни немного за csv файл. В каком виде там изображения, обрабатывал ли ты их как-то предварительно

И насколько я знаю, вроде всегда называют README.md

2023-09-26 18:24 UTC, AntonIV8 commented on src/PyTorchClassifierCSVDataset/main.py
> +class CustomCSVDataset(Dataset):
Ну тут конечно да, но я думаю такие штуки много времени занять могут, я вот долго проплюхался и то не врубил, как красивше оформить функции, чтобы не были вложенными. Поэтому сомневаюсь, что нужно. Это же чисто пример для колаба (в ридми бы еще это упомянуть)

2023-09-27 10:20 UTC, BannikovRuslan approved these changes

2023-10-09 04:45 UTC, AntonIV8 approved these changes

2023-10-09 04:45 UTC, merged