Добавлен PyTorch классификатор изображений
Flexberry/Flexberry.TextClassifierAI.Sample pull request #24
Opened 2023-09-27 04:25 UTC by neroslovegor

2023-09-27 10:23 UTC, BannikovRuslan approved these changes

2023-10-02 04:43 UTC, AntonIV8 requested changes

2023-10-02 04:43 UTC, AntonIV8 commented on src/ImageClassifiers/PyTorchImageClassifierWithFileDataset/README.md
> +Этот проект представляет собой пример использования нейронной сети для классификации изображений с использованием библиотеки PyTorch и предварительно обученной модели ResNet-18. Проект включает в себ
обработку и классификациЮ

2023-10-02 05:26 UTC, AntonIV8 approved these changes

2023-10-02 05:26 UTC, merged